require "capita/one_digital/operations/delete_profile"
require "capita/one_digital/operations/edit_profile"
require "capita/one_digital/operations/login"
require "capita/one_digital/operations/login_status"
require "capita/one_digital/operations/logout"
require "capita/one_digital/operations/profile"
require "capita/one_digital/operations/register"
